name: ROS 2 Build Test

on:
  push:
    branches: [ main, 'fix/**', 'feat/**']
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ros_distro: [humble]

    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}

      - uses: actions/checkout@v3
        with:
          path: src/nautronics_auv

      - name: Import External Repositories
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-vcstool
          cd src
          
          # .repos dosyasını dinamik olarak bul
          REPO_FILE=$(find nautronics_auv -name "nautronics.repos" | head -n 1)
          
          if [ -z "$REPO_FILE" ]; then
            echo "::warning::nautronics.repos dosyası bulunamadı."
          else
            echo "Dosya bulundu: $REPO_FILE"
            vcs import < "$REPO_FILE"
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          
          REQ_FILE=$(find src -name "requirements.txt" | head -n 1)
          
          if [ -z "$REQ_FILE" ]; then
             echo "::warning::requirements.txt bulunamadı, pip kurulumu atlanıyor."
          else
             echo "Python gereksinimleri kuruluyor: $REQ_FILE"
             pip3 install -r "$REQ_FILE"
          fi

          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      # 5. Derle
      - name: Build Workspace
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install