name: ROS 2 Build Test

on:
  push:
    branches: [ main, 'fix/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ros_distro: [humble]

    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}

      - uses: actions/checkout@v3
        with:
          path: src/nautronics_auv

      - name: Import External Repositories
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-vcstool
          cd src
          
          # AKILLI ÇÖZÜM: Dosyayı nerede olursa olsun buluyoruz
          # (İster root'ta olsun ister src içinde)
          REPO_FILE=$(find nautronics_auv -name "nautronics.repos" | head -n 1)
          
          if [ -z "$REPO_FILE" ]; then
            echo "::error::nautronics.repos dosyası bulunamadı! Dosya yapısı listeleniyor:"
            ls -R nautronics_auv
            exit 1
          else
            echo "Dosya bulundu: $REPO_FILE"
            vcs import < "$REPO_FILE"
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build Workspace
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install